### ISSUE TITLE
Allow patterns for defining the sorting order

### ISSUE THREAD

**Issue by lobo-tuerto** [heybourn/headwind#76] opened 2020-06-04 16:20 UTC
I think it would be much better to be able to specify an entire class space with something like `text-*` instead of listing all the existing `text-blue-100` `text-blue-200` which leaves out any custom color classes you might add.

In this way you would _glob_ all the `text-*` and proceed to sort then alphabetically, all user added new colors would be taken into account.

Of course, this is a very simplistic solution, but the idea behind it (using patterns to describe the sorting order) is something that could be very useful.

Right now the sort order defined in `package.json` is only for the TailwindCSS vanilla classes.
With a pattern matching approach, you would be able to consider any new additions the user make.

Thoughts?

**Comment by hacknug** [comment] 2020-06-09 11:17
Duplicate of #5 ?

**Comment by heybourn** [comment] 2020-07-08 22:58
Closing this as it's very similar to #5. Feel free to reopen if you think otherwise!

**Closed by heybourn** 2020-07-08 22:58 UTC
